<link rel="stylesheet" href="/public/css/admin/form.css" media="screen" title="no title" charset="utf-8">
<link rel="stylesheet" href="/public/css/articles/form.css" media="screen" title="no title" charset="utf-8">
<link rel="stylesheet" href="/public/css/articles/responsive.css" media="screen" title="no title" charset="utf-8">
<link rel="stylesheet" href="/public/css/plugins/tooltip-1.0.css" media="screen">
<link rel="stylesheet" href="/public/css/plugins/progressbar-1.0.css" media="screen">
<link rel="stylesheet" href="/public/css/plugins/dropify-1.1.css" media="screen">
<link rel="stylesheet" href="/public/javascript/plugins/jquery-ui/jquery-ui.min.css" media="screen">
<script src="/public/javascript/plugins/ckeditor/ckeditor.js" charset="utf-8"></script>
<script src="/public/javascript/plugins/jquery-ui/jquery-ui.min.js" charset="utf-8"></script>
<script src="/public/javascript/plugins/helium.tooltip-1.0.js" charset="utf-8"></script>
<script src="/public/javascript/plugins/helium.progressbar-1.0.js" charset="utf-8"></script>
<script src="/public/javascript/plugins/helium.dropify-1.1.js" charset="utf-8"></script>
<script src="/public/javascript/plugins/helium.browser-1.0.js" charset="utf-8"></script>
<script src="/public/javascript/helium.articles.js" charset="utf-8"></script>
<script src="/public/javascript/helium.form.js" charset="utf-8"></script>
<script src="/public/javascript/helium.ajax.js" charset="utf-8"></script>
<script src="/public/javascript/helium.image.js" charset="utf-8"></script>
