<link rel="stylesheet" href="/public/css/user/add.css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="/public/css/plugins/tooltip-1.0.css" media="screen">
    <script src="/public/javascript/helium.form.js" charset="utf-8"></script>
    <script src="/public/javascript/plugins/helium.tooltip-1.0.js" charset="utf-8"></script>
    <script src="/public/javascript/plugins/helium.browser-1.0.js" charset="utf-8"></script>
