<link rel="stylesheet" href="/public/css/gallery/upload.css" media="screen" charset="utf-8">
<link rel="stylesheet" href="/public/css/plugins/tooltip-1.0.css" media="screen">
<link rel="stylesheet" href="/public/css/plugins/progressbar-1.0.css" media="screen">
<link rel="stylesheet" href="/node_modules/dropster/lib/dropster.css" media="screen">
<script src="/node_modules/dropster/lib/dropster.js" charset="utf-8"></script>
<script src="/public/javascript/plugins/helium.progressbar-1.0.js" charset="utf-8"></script>
<script src="/public/javascript/helium.image.js" charset="utf-8"></script>
<script src="/public/javascript/helium.gallery.js" charset="utf-8"></script>
