<link rel="stylesheet" href="/node_modules/dropster/lib/dropster.css" media="screen" charset="utf-8">
<link rel="stylesheet" href="/node_modules/salvation/lib/salvation.css" media="screen" charset="utf-8">
<link rel="stylesheet" href="/public/css/admin/form.css" media="screen" charset="utf-8">
<link rel="stylesheet" href="/public/css/posts/main.css" media="screen" charset="utf-8">
<script type="text/javascript" src="/public/javascript/plugins/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/node_modules/dropster/lib/dropster.js"></script>
<script type="text/javascript" src="/node_modules/salvation/lib/salvation.min.js"></script>
<script type="text/javascript" src="/public/javascript/image.js"></script>
